-- FORALL

/*
CREATE TABLE HR.EMPLOYEE_HISTORY(EMPLOYEE_ID INTEGER PRIMARY KEY, SALARY NUMBER(8,2), HIRE_DATE DATE);
CREATE TABLE EMPLOYEE2 AS SELECT * FROM HR.EMPLOYEES;
INSERT INTO HR.EMPLOYEE_HISTORY (EMPLOYEE_ID, SALARY, HIRE_DATE) VALUES (1, 999999.99, SYSDATE);
*/

SET SERVEROUTPUT ON;

DECLARE
TYPE tblEmp IS TABLE OF HR.EMPLOYEES%ROWTYPE;
lstEmp tblEmp;
BEGIN

  SELECT * BULK COLLECT INTO lstEmp FROM HR.EMPLOYEES;
 
  FORALL IDX IN INDICES OF LSTEMP SAVE EXCEPTIONS
      INSERT INTO HR.EMPLOYEE_HISTORY (EMPLOYEE_ID, SALARY, HIRE_DATE) VALUES (LSTEMP(IDX).EMPLOYEE_ID, LSTEMP(IDX).SALARY, LSTEMP(IDX).HIRE_DATE) ;

  COMMIT;

  EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro ao incluir:' || SQLERRM);
    ROLLBACK;
END;
/