MERGE INTO HR.EMPLOYEES2            ENEW
USING (SELECT * FROM HR.EMPLOYEES)  EOLD
   ON (ENEW.EMPLOYEE_ID = EOLD.EMPLOYEE_ID)
WHEN MATCHED THEN
  UPDATE SET ENEW.SALARY = EOLD.SALARY
  DELETE WHERE (EOLD.SALARY < 3000)
WHEN NOT MATCHED THEN
INSERT (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
 VALUES (EOLD.EMPLOYEE_ID, EOLD.FIRST_NAME, EOLD.LAST_NAME, EOLD.EMAIL, EOLD.PHONE_NUMBER, EOLD.HIRE_DATE, EOLD.JOB_ID, EOLD.SALARY, EOLD.COMMISSION_PCT, EOLD.MANAGER_ID, EOLD.DEPARTMENT_ID);

SELECT COUNT(1) FROM HR.EMPLOYEES2 WHERE SALARY < 3000;
SELECT COUNT(1) FROM HR.EMPLOYEES  WHERE SALARY < 3000;


MERGE INTO HR.EMPLOYEES2           EMPNEW
USING (SELECT * FROM HR.EMPLOYEES) EMPOLD
   ON (EMPNEW.EMPLOYEE_ID = EMPOLD.EMPLOYEE_ID)
WHEN MATCHED THEN
  UPDATE SET EMPNEW.FIRST_NAME = EMPOLD.FIRST_NAME, EMPNEW.LAST_NAME = EMPOLD.LAST_NAME, EMPNEW.EMAIL = EMPOLD.EMAIL,
             EMPNEW.PHONE_NUMBER = EMPOLD.PHONE_NUMBER, EMPNEW.HIRE_DATE = EMPOLD.HIRE_DATE, EMPNEW.JOB_ID = EMPOLD.JOB_ID, EMPNEW.SALARY = EMPOLD.SALARY,
             EMPNEW.COMMISSION_PCT = EMPOLD.COMMISSION_PCT, EMPNEW.MANAGER_ID = EMPOLD.MANAGER_ID, EMPNEW.DEPARTMENT_ID = EMPOLD.DEPARTMENT_ID
WHEN NOT MATCHED THEN
 INSERT (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
 VALUES (EMPOLD.EMPLOYEE_ID, EMPOLD.FIRST_NAME, EMPOLD.LAST_NAME, EMPOLD.EMAIL, EMPOLD.PHONE_NUMBER, EMPOLD.HIRE_DATE, EMPOLD.JOB_ID, EMPOLD.SALARY, EMPOLD.COMMISSION_PCT, EMPOLD.MANAGER_ID, EMPOLD.DEPARTMENT_ID);


SELECT * FROM HR.EMPLOYEES WHERE EMPLOYEE_ID = 100;
SELECT * FROM HR.EMPLOYEES2 WHERE EMPLOYEE_ID = 100;
UPDATE HR.EMPLOYEES SET LAST_NAME = 'King' WHERE EMPLOYEE_ID = 100;


